AHCWebApp/Project2/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project2.Models
{
    public class Order
    {
        public int Id { get; set; }
        public DateTime PeriodDate { get; set; }
        public string PeriodLabel { get; set; }
        public int Ordered { get; set; }
        public int Shipped { get; set; }
        public decimal TotalOrderedAmount { get; set; }
        public decimal TotalShippedAmount { get; set; }
    }
}

AHCWebApp/Project2/ViewModels/OrderSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Project2.Models;

namespace Project2.ViewModels
{
    public class OrderSummaryViewModel
    {
        public List<Order> orders;
        public decimal? orderAvg { get; set; }
        public decimal? orderTotal { get; set; }
        public decimal? shippedAvg { get; set; }
        public decimal? shippedTotal { get; set; }
        
    }
}

AHCWebApp/Project2/Controllers/OrderSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using Project2.Models;
using System.Web.Script.Serialization;
using System.Threading.Tasks;
using System.Data;
using System.IO;
using Project2.ViewModels;

namespace Project2.Controllers
{
    public class OrderSummaryController : Controller
    {
        static string _address = "http://ahcwebapi.azurewebsites.net";
        OrderSummaryViewModel orderDetails = new OrderSummaryViewModel();
       
        private void GetData(string uri)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(_address);
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
            var task = client.GetAsync(uri)
              .ContinueWith((taskwithresponse) =>
              {
                  var response = taskwithresponse.Result;
                  var jsonString = response.Content.ReadAsStringAsync();
                  var js = new JavaScriptSerializer();
                  var deserializedOrders = js.Deserialize<List<Order>>(jsonString.Result);
                  orderDetails.orders = deserializedOrders;
              });
            task.Wait();
            UpdateAggregates();
        }
        
        private void UpdateAggregates() {
            orderDetails.orderTotal = Math.Round(orderDetails.orders.Sum(item => item.TotalOrderedAmount), 2);
            orderDetails.orderAvg = Math.Round(Convert.ToDecimal(orderDetails.orderTotal / orderDetails.orders.Sum(item => item.Ordered)), 2);
            orderDetails.shippedTotal = Math.Round(orderDetails.orders.Sum(item => item.TotalOrderedAmount),2);
            orderDetails.shippedAvg = Math.Round(Convert.ToDecimal(orderDetails.shippedTotal/orderDetails.orders.Sum(item => item.Shipped)), 2);
            return;
        }

        public ActionResult Index()
        {
            GetData("/api/ordersummary/weekoverweek");
            return View(orderDetails);
        }

        public ActionResult Month()
        {
            GetData("/api/ordersummary/monthovermonth");
            return View(orderDetails);
        }

        public ActionResult Year()
        {
            GetData("/api/ordersummary/yearoveryear");
            return View(orderDetails);
        }
    }
}

AHCWebApp/Project2/Views/OrderSummary/Index.cshtml
@using System.Web.Helpers;

@model Project2.ViewModels.OrderSummaryViewModel
@{
    ViewBag.Title = "Order Summary";
}
<div id="orderSummaryContent">
    <div>
      <div id="line-chart"></div>
    </div>
  <div id="aggregates">
  <table class="tableAggregates">
  <tbody>
               <tr>
                <td>
                    <p class="block">
                        <label class="content">$@Model.orderAvg</label><br />
                        <label class="heading">Average Order Amount</label>
                    </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.orderTotal</label><br />
                        <label class="heading">Total Order Amount</label>
                    </p>
                </td>
                <td>
                      <p class="block">
                        <label class="content">$@Model.shippedAvg</label><br />
                        <label class="heading">Average Shipped Amount</label>
                     </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.shippedTotal</label><br />
                        <label class="heading">Total Shipped Amount</label>
                     </p>
                </td>
               </tr>
    </tbody>
    </table>
</div>

<table class="table table-striped table-bordered ">
    <tbody>
        <tr>
                    <th class="col-md-2">Period</th>
                    <th class="col-md-2">Ordered</th>
                    <th class="col-md-2">Shipped</th>
                    <th class="col-md-2">TotalOrderedAmount</th>
                    <th class="col-md-2">TotalShippedAmount</th>
        </tr>
        @foreach (var item in Model.orders)
        {
               <tr>
                <td class="col-md-2">@item.PeriodLabel</td>
                <td class="col-md-2">@item.Ordered</td>
                <td class="col-md-2">@item.Shipped</td>
                <td class="col-md-2">@item.TotalOrderedAmount</td>
                <td class="col-md-2">@item.TotalShippedAmount</td>
               </tr>
                
        }
    </tbody>
</table>
</div>


<script type="text/javascript">
    var jsModel = '@Html.Raw(Json.Encode(@Model.orders))';
    


</script>

AHCWebApp/Project2/Views/OrderSummary/Month.cshtml
@using System.Web.Helpers;

@model Project2.ViewModels.OrderSummaryViewModel
@{
    ViewBag.Title = "Order Summary";
}
<div id="orderSummaryContent">
    <div>
      <div id="line-chart"></div>
    </div>
  <div id="aggregates">
  <table class="tableAggregates">
  <tbody>
               <tr>
                <td>
                    <p class="block">
                        <label class="content">$@Model.orderAvg</label><br />
                        <label class="heading">Average Order Amount</label>
                    </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.orderTotal</label><br />
                        <label class="heading">Total Order Amount</label>
                    </p>
                </td>
                <td>
                      <p class="block">
                        <label class="content">$@Model.shippedAvg</label><br />
                        <label class="heading">Average Shipped Amount</label>
                     </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.shippedTotal</label><br />
                        <label class="heading">Total Shipped Amount</label>
                     </p>
                </td>
               </tr>
    </tbody>
    </table>
</div>

<table class="table table-striped table-bordered ">
    <tbody>
        <tr>
                    <th class="col-md-2">Period</th>
                    <th class="col-md-2">Ordered</th>
                    <th class="col-md-2">Shipped</th>
                    <th class="col-md-2">TotalOrderedAmount</th>
                    <th class="col-md-2">TotalShippedAmount</th>
        </tr>
        @foreach (var item in Model.orders)
        {
               <tr>
                <td class="col-md-2">@item.PeriodLabel</td>
                <td class="col-md-2">@item.Ordered</td>
                <td class="col-md-2">@item.Shipped</td>
                <td class="col-md-2">@item.TotalOrderedAmount</td>
                <td class="col-md-2">@item.TotalShippedAmount</td>
               </tr>
                
        }
    </tbody>
</table>
</div>


<script type="text/javascript">
    var jsModel = '@Html.Raw(Json.Encode(@Model.orders))';
    


</script>

AHCWebApp/Project2/Views/OrderSummary/Year.cshtml
@using System.Web.Helpers;

@model Project2.ViewModels.OrderSummaryViewModel
@{
    ViewBag.Title = "Order Summary";
}
<div id="orderSummaryContent">
    <div>
      <div id="line-chart"></div>
    </div>
  <div id="aggregates">
  <table class="tableAggregates">
  <tbody>
               <tr>
                <td>
                    <p class="block">
                        <label class="content">$@Model.orderAvg</label><br />
                        <label class="heading">Average Order Amount</label>
                    </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.orderTotal</label><br />
                        <label class="heading">Total Order Amount</label>
                    </p>
                </td>
                <td>
                      <p class="block">
                        <label class="content">$@Model.shippedAvg</label><br />
                        <label class="heading">Average Shipped Amount</label>
                     </p>
                </td>
                <td>
                     <p class="block">
                        <label class="content">$@Model.shippedTotal</label><br />
                        <label class="heading">Total Shipped Amount</label>
                     </p>
                </td>
               </tr>
    </tbody>
    </table>
</div>
<table class="table table-striped table-bordered ">
    <tbody>
        <tr>
                    <th class="col-md-2">Period</th>
                    <th class="col-md-2">Ordered</th>
                    <th class="col-md-2">Shipped</th>
                    <th class="col-md-2">TotalOrderedAmount</th>
                    <th class="col-md-2">TotalShippedAmount</th>
        </tr>
        @foreach (var item in Model.orders)
        {
               <tr>
                <td class="col-md-2">@item.PeriodLabel</td>
                <td class="col-md-2">@item.Ordered</td>
                <td class="col-md-2">@item.Shipped</td>
                <td class="col-md-2">@item.TotalOrderedAmount</td>
                <td class="col-md-2">@item.TotalShippedAmount</td>
               </tr>
                
        }
    </tbody>
</table>
</div>


<script type="text/javascript">
    var jsModel = '@Html.Raw(Json.Encode(@Model.orders))';
    


</script>

AHCWebApp/Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js" type ="text/javascript"></script>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<h1 style="text-align: center;">AHC Web Developer Exam</h1>
<hr />
 <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <nav class="navbar navbar-default navbar-custom">
                      <div class="container-fluid">
                        <div class="navbar-header">
                          <a class="navbar-brand" href="#">Order Summary</a>
                        </div>
                        <div>
                          <ul class="nav navbar-nav navbar-right">
                            <li id="week"><a href='@Url.Action("", "OrderSummary")'>By Week</a></li>
                            <li id="month"><a href='@Url.Action("Month", "OrderSummary")'>By Month</a></li>
                            <li id="year"><a href='@Url.Action("Year", "OrderSummary")'>By Year</a></li>
                            @*<li><a href="#" data-bind="click: $parent.getDataByMonth">By Month</a></li>*@
                          </ul>
                        </div>
                      </div>
                  </nav>


                 <div class="span9">
                <div class="row-fluid"><br />
                @RenderBody()
                    </div>
            </div>
                <!--/.well -->
            </div>
            <!--/span-->
            <!--/span-->
        </div>
        <!--/row-->
    </div><!--/.fluid-container-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
<script src="../../Scripts/knockout-2.1.0.js" type="text/javascript"></script>
<script src="../../Scripts/application.js" type="text/javascript"></script>
</html>
